language: go

go:
  - 1.0
  - 1.1
  - 1.2
  - 1.3
  - tip

install:
  - sudo apt-get update
  - sudo apt-get upgrade -f -y
  - sudo apt-get install -f -y mosquitto
  - go get -d -v ./...
script:
  - go test -v
